spring.application.name=API-GATEWAY

server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ===========================
# Gateway Routes
# ===========================

# Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# Doctor Service
spring.cloud.gateway.server.webflux.routes[1].id=doctor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/doctors/**

# Patient Service
spring.cloud.gateway.server.webflux.routes[2].id=patient-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/patients/**